import AppKit

struct ClipItem: Identifiable, Hashable, Sendable {
    enum Kind: Int, Sendable {
        case text = 0
        case image = 1
        case files = 2
    }

    let id: String
    let kind: Kind
    /// Text content, or newline-separated paths for `.files`.
    let text: String?
    /// File name inside the store's image directory.
    let imageFile: String?
    let pixelSize: CGSize?
    let hash: String
    let sourceBundleID: String?
    var date: Date

    /// Precomputed one-line summary so list rows never scan large strings while rendering.
    let title: String

    init(id: String, kind: Kind, text: String?, imageFile: String?, pixelSize: CGSize?, hash: String, sourceBundleID: String?, date: Date) {
        self.id = id
        self.kind = kind
        self.text = text
        self.imageFile = imageFile
        self.pixelSize = pixelSize
        self.hash = hash
        self.sourceBundleID = sourceBundleID
        self.date = date
        self.title = Self.makeTitle(kind: kind, text: text, pixelSize: pixelSize)
    }

    var fileURLs: [URL] {
        guard kind == .files, let text else { return [] }
        return text.split(separator: "\n").map { URL(fileURLWithPath: String($0)) }
    }

    private static func makeTitle(kind: Kind, text: String?, pixelSize: CGSize?) -> String {
        switch kind {
        case .text:
            let prefix = (text ?? "").prefix(400)
            let line = prefix.split(whereSeparator: \.isNewline)
                .first { !$0.allSatisfy(\.isWhitespace) } ?? ""
            return line.trimmingCharacters(in: .whitespaces)
        case .image:
            guard let size = pixelSize else { return "Image" }
            return "Image \(Int(size.width))×\(Int(size.height))"
        case .files:
            let names = (text ?? "").split(separator: "\n").map { ($0 as NSString).lastPathComponent }
            return names.count == 1 ? names[0] : "\(names.count) files"
        }
    }
}

/// What was read off the pasteboard, before it is persisted.
enum ClipCapture: Sendable {
    case text(String)
    case image(Data, isPNG: Bool)
    case files([URL])

    /// Markers apps (password managers etc.) put on data that must not be recorded.
    /// See http://nspasteboard.org
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    static func read(from pasteboard: NSPasteboard) -> ClipCapture? {
        guard let types = pasteboard.types, !types.isEmpty else { return nil }
        if types.contains(where: { ignoredTypes.contains($0.rawValue) }) { return nil }

        if types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        // Prefer text when both exist: rich-text and spreadsheet apps attach image renditions too.
        if let string = pasteboard.string(forType: .string),
           !string.allSatisfy(\.isWhitespace) {
            return .text(string.count > Config.maxTextLength ? String(string.prefix(Config.maxTextLength)) : string)
        }
        if let png = pasteboard.data(forType: .png), png.count <= Config.maxImageBytes {
            return .image(png, isPNG: true)
        }
        if let tiff = pasteboard.data(forType: .tiff), tiff.count <= Config.maxImageBytes {
            return .image(tiff, isPNG: false)
        }
        return nil
    }
}
